version: "3.8"
services:
  quiz-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    command: npm start

  test-runner:
    build:
      context: .
    environment:
      - NODE_ENV=test
    volumes:
      - .:/usr/src/app
    command: npm test
